services:
  postgres:
    image: postgres:16
    container_name: hcms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hcms
      POSTGRES_USER: hcms_user
      POSTGRES_PASSWORD: hcms_pass
      
    ports:
      - "5433:5432"
    volumes:
      - hcms-pgdata:/var/lib/postgresql/data
volumes:
  hcms-pgdata: